[package]
name = "cofd-macros"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
cofd-schema.workspace = true

proc-macro2 = "1"
quote = "1"
syn = "2"

ron.workspace = true

convert_case.workspace = true